package org.uff.minijava;

public enum Token {
    CLASS, PUBLIC, STATIC, VOID, MAIN, STRING, EXTENDS, RETURN, INT, BOOLEAN, IF, ELSE, WHILE,
    SYSTEM_OUT_PRINTLN, LENGTH, TRUE, FALSE, THIS, NEW,

    ID,

    INTEGER_LITERAL,

    PLUS, MINUS, TIMES, DIVIDE, AND, LESS_THAN, NOT_EQUAL, ASSIGN,

    LPAREN, RPAREN, LBRACE, RBRACE, LBRACKET, RBRACKET, SEMICOLON, DOT, COMMA,

    EOF,
    ERROR
}
